window.siteConfig = {
  heroImages: [
    {
      src: "assets/cases/large/case-01-large.jpg",
      alt: "科研图形摘要首页展示图",
    },
    {
      src: "assets/cases/large/case-08-large.jpg",
      alt: "生物材料机制示意首页展示图",
    },
    {
      src: "assets/cases/large/case-05-large.jpg",
      alt: "期刊封面首页展示图",
    },
  ],
  cases: [
    ["北京大学", "Advanced Science · 2025", "骨修复 / 3D机制示意", "mechanism render abstract"],
    ["东华大学", "ACS Nano · 2025", "纳米材料 / 期刊封面", "cover figure"],
    ["天津大学", "Advanced Materials · 2025", "信息材料 / 3D封面视觉", "cover render"],
    ["郑州大学", "Advanced Materials · 2025", "柔性传感 / 封面视觉", "cover render"],
    ["东北大学", "Angewandte Chemie · 2025", "腐蚀科学 / 期刊封面", "cover render"],
    ["东北林业大学", "Advanced Functional Materials · 2025", "功能材料 / 图形摘要", "abstract mechanism figure"],
    ["北京科技大学", "Chemical Engineering Journal · 2025", "化工材料 / 机制拆解", "mechanism render"],
    ["华中科技大学", "Biomaterials · 2025", "生物材料 / 结构机制", "mechanism render abstract"],
    ["吉林大学", "Advanced Materials · 2025", "材料科学 / 论文图组", "abstract figure"],
    ["哈尔滨工业大学", "Renewable and Sustainable Energy Reviews · 2025", "能源环境 / 综述图示", "abstract mechanism"],
    ["中国农业大学", "Analytical Chemistry · 2025", "分析检测 / 论文图组", "abstract mechanism figure"],
    ["中山大学", "Advanced Functional Materials · 2025", "生物医学 / 3D示意", "abstract render"],
    ["西安交通大学", "Advanced Energy Materials · 2025", "能源材料 / 期刊封面", "cover render"],
    ["南京大学", "Nature Communications · 2025", "化学机制 / 论文图组", "cover figure"],
    ["复旦大学", "Advanced Science · 2025", "细胞治疗 / 图形摘要", "abstract render mechanism"],
    ["上海交通大学", "Small · 2025", "纳米结构 / 机制示意", "mechanism figure"],
    ["浙江大学", "Nano Letters · 2025", "微纳材料 / 论文图组", "abstract mechanism figure"],
    ["四川大学", "Biomaterials · 2025", "生物材料 / 图形摘要", "abstract figure"],
    ["同济大学", "Advanced Materials · 2025", "工程材料 / 3D渲染", "abstract render"],
    ["中国科学院", "Chemical Society Reviews · 2025", "综述机制 / 信息图", "abstract mechanism figure"],
    ["南开大学", "Journal of Materials Chemistry A · 2025", "能源催化 / 机制图", "abstract mechanism"],
    ["厦门大学", "Energy & Environmental Science · 2025", "能源环境 / 3D机制", "abstract mechanism render"],
    ["山东大学", "ACS Applied Materials & Interfaces · 2025", "材料界面 / 机制示意", "abstract mechanism"],
    ["武汉大学", "Advanced Healthcare Materials · 2025", "医学材料 / 论文图组", "abstract figure"],
    ["华南理工大学", "Matter · 2025", "智能材料 / 3D图示", "abstract render"],
    ["重庆大学", "Carbon · 2025", "碳材料 / 结构机制", "abstract mechanism"],
    ["苏州大学", "Advanced Functional Materials · 2025", "柔性器件 / 期刊封面", "cover render"],
    ["兰州大学", "Environmental Science & Technology · 2025", "环境科学 / 论文图组", "abstract mechanism figure"],
  ],
};
